// KitchenKanban.WebUI/kitchenreact/src/_components/MessageError.jsx
import React from 'react';
import { Link } from 'react-router-dom';
import { connect } from 'react-redux';
import { itemsListActions,orderActions } from '../_actions';
import { Header } from '../_components/Header';
class MessageError extends React.Component {
     constructor(props) {
        super(props); 
      
        this.state={
                 showmessage:false  
        };  
        
     
    
    }
  componentDidMount () 
    {  
         this.setState({
          showmessage:this.props.showerrorform
      })
      
 
       
    }
    componentDidUpdate(nextprops,prevprops){         
        setTimeout(() =>this.props.handler(false) , 
            1000);
    }
    
    render() {
              const {showErrorform,msg} = this.props;
        const {showmessage}=this.state;      

        return (
        <div>
    {showmessage  &&
        <div className="overlay">
        <div className="pop-overlay">
                    <div className="error-header">
                        <img src="images/error.png" />
                    </div>
                    <div className="text-center pop-header">Error!</div>
                    <div className="text-center">{msg}</div>
                
            </div>
    </div>
          
    }
          </div>
        );
    }
}

function mapStateToProps(state) {
    const {  } = state;
    return {
         
    };
}

const connectedMessageError = connect(mapStateToProps)(MessageError);
export { connectedMessageError as MessageError };

// KitchenKanban.WebUI/kitchenvue/src/components/MessageError.vue
<template>
<div>
    <div class="overlay">
        <div class="pop-overlay">
                    <div class="error-header">
                        <img src="../assets/images/error.png" />
                    </div>
                    <div class="text-center pop-header">Error!</div>
                    <div class="text-center">{{msg}}</div>
                    <div class="text-center">
                        <button class="error-btn" @click="onContinue">Continue</button>
                    </div>
            </div>
    </div>
</div>
</template>
<script>
export default {
  name: 'MessageError',
  props: {
    msg: String
  },
  methods:{
    onContinue:function(){
      this.$router.go()
    }
  }
}
</script>
