// KitchenKanban.WebUI/kitchenangular/src/app/components/reports/reports.component.ts
import { Component, OnInit } from '@angular/core';
import { ReportService } from '../../services/report.service';
import { MessageService } from '../../services/message.service';
import { OrderService } from '../../services/order.service';

@Component({
  selector: 'app-reports',
  templateUrl: './reports.component.html',
  styleUrls: ['./reports.component.css']
})
export class ReportsComponent implements OnInit {

  orderStatues: Array<{ id: number, text: string }> = [
    { id: 1, text: 'New Order' },
    { id: 2, text: 'Being Prepared' },
    { id: 3, text: 'Prepared' },
    { id: 4, text: 'Packing' },
    { id: 5, text: 'Ready To Be Delivered' },
    { id: 6, text: 'Delivered' },
    { id: 7, text: 'Cancelled' }
  ];
  orders: any = [];
  showPopup = false;
  recordNotFound = false;
  record = {
    order: {
      orderId: null,
      orderNumber: null,
      orderStatus: 0,
      orderType: 2,
      orderAmount: 0,
      orderDeliveryDate: null,
      orderDate: null,
      orderTakenByUserName: null,
      customerName: '',
      customerContactNumber: ''
    },
    orderLines: []
  };  
  orderLineItems: any = [];

  currentDate = new Date();
  constructor(private reportService: ReportService, private messageService: MessageService,
    private orderService: OrderService) { }

  ngOnInit(): void {
    this.getOrderReport();
  }

  getOrderReport(): void {
    this.reportService.getOrderReport().subscribe(
      data => {
        this.orders = data;
        if (this.orders.length > 0) {
          this.recordNotFound = false;
        }
        else {
          this.recordNotFound = true;
        }
      },
      err => {
        console.log("Report getOrderReport : ", err)
        this.messageService.showErrorMessage(err.Message);
      }
    );
  }

  getTotalDishesCount() {
    if (this.orders) {
      return this.orders.map((t: { noOfItemsInOrder: any; }) => t).reduce((a: any, value: any) => a + value.noOfItemsInOrder, 0);
    }
    return 0;
  }

  getTotalAmount() {
    if (this.orders) {
      return this.orders.map((t: { orderAmount: any; }) => t).reduce((a: any, value: any) => a + value.orderAmount, 0);
    }
    return 0;
  }

  getOrderStatus(orderStatus: number): string {
    let selectedorderStatus = this.orderStatues.find(x => x.id == orderStatus);
    return selectedorderStatus == null ? "" : selectedorderStatus.text;
  }

  showReportDetail(orderId: string) {
    this.orderService.getOrderById(orderId).subscribe(
      data => {
        this.record = data;
        this.orderLineItems = data.orderLines;
        if (this.record.order.customerName != null) {
          var regex = /\b(\w{2})(\w+)(\w)\b/g;
          this.record.order.customerName = (this.record.order.customerName.replace(regex, (_, first, middle, last) => `${first}${'x'.repeat(middle.length)}${last}`));
        }
        if (this.record.order.customerContactNumber != null) {
          var regex = /\b(\w{2})(\w+)(\w)\b/g;
          this.record.order.customerContactNumber = (this.record.order.customerContactNumber.replace(regex, (_, first, middle, last) => `${first}${'x'.repeat(middle.length)}${last}`));
        }
        this.showPopup = true;
      },
      err => {
        console.log("Report showReportDetail : ", err)
        this.messageService.showErrorMessage(err.Message);
      }
    );
  }

  getItemTotalAmount(quantity: any, price: any) {
    return (quantity * price);
  }

  getTotalItems() {
    if (this.record.orderLines) {
      return this.record.orderLines.map((t: { orderQuantity: any; }) => t).reduce((a: any, value: any) => a + value.orderQuantity, 0);
    }
    return 0;
  }

  getTotalLineAmount() {
    if (this.record.orderLines) {
      return this.record.orderLines.map((t: { orderQuantity: any; }) => t).reduce((a: any, value: any) => a + (value.orderQuantity * value.itemCharge), 0);
    }
    return 0;
  }

  closeForm(): void {
    this.showPopup = false;
    this.record = {
      order: {
        orderId: null,
        orderNumber: null,
        orderStatus: 0,
        orderType: 2,
        orderAmount: 0,
        orderDeliveryDate: null,
        orderDate: null,
        orderTakenByUserName: null,
        customerName: '',
        customerContactNumber: ''
      },
      orderLines: []
    };
  }

}

<div>
    <section>
        <div class="breadcrumb">Reports</div>
        <div class="list-sec">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-3">
                        &nbsp;
                    </div>
                    <div class="col-xs-6 text-center current-date">
                        07/12/2020
                    </div>
                    <div class="col-xs-3">
                        <input type="search" placeholder="Search Order" class="form-control" />
                    </div>
                </div>
            </div>
            <table class="custom-tbl">
                <tr>
                    <th class="text-center">Sl No</th>
                    <th class="text-center">Order No</th>
                    <th class="text-center">Order Time</th>
                    <th class="text-center">No of Dishes</th>
                    <th class="text-center">Order Taken By</th>
                    <th class="text-center">Order Value</th>
                    <th class="text-center">Order Status</th>
                    <th class="text-center">Detail</th>
                </tr>
                <tr class="custom-btl-row">
                    <td class="text-center">01</td>
                    <td>120820-001</td>
                    <td>09.20 am</td>
                    <td class="text-center">03</td>
                    <td>Pramod Karkera</td>
                    <td class="text-right">$150.00</td>
                    <td class="text-center">Delivered</td>
                    <td class="text-center">
                        <button class="trans-btn" data-toggle="modal" data-target="#reportDetail"><i
                                class="glyphicon glyphicon-exclamation-sign"></i></button>
                    </td>
                </tr>
                <tr class="custom-btl-row">
                    <td class="text-center">02</td>
                    <td>120820-002</td>
                    <td>10.13 am</td>
                    <td class="text-center">03</td>
                    <td>Pramod Karkera</td>
                    <td class="text-right">$150.00</td>
                    <td class="text-center cancelled-order-status">Cancelled</td>
                    <td class="text-center">
                        <button class="trans-btn" data-toggle="modal" data-target="#reportDetail"><i
                                class="glyphicon glyphicon-exclamation-sign"></i></button>
                    </td>
                </tr>
                <tr class="custom-btl-row">
                    <td class="text-center">03</td>
                    <td>120820-003</td>
                    <td>10.22 am</td>
                    <td class="text-center">03</td>
                    <td>Pramod Karkera</td>
                    <td class="text-right">$150.00</td>
                    <td class="text-center">Preparing</td>
                    <td class="text-center">
                        <button class="trans-btn" data-toggle="modal" data-target="#reportDetail"><i
                                class="glyphicon glyphicon-exclamation-sign"></i></button>
                    </td>
                </tr>
                <tr class="custom-btl-row">
                    <td class="text-center">04</td>
                    <td>120820-004</td>
                    <td>11.15 am</td>
                    <td class="text-center">03</td>
                    <td>Pramod Karkera</td>
                    <td class="text-right">$150.00</td>
                    <td class="text-center">Packing</td>
                    <td class="text-center">
                        <button class="trans-btn" data-toggle="modal" data-target="#reportDetail"><i
                                class="glyphicon glyphicon-exclamation-sign"></i></button>
                    </td>
                </tr>
                <tr class="custom-btl-row">
                    <td class="text-center bold">04</td>
                    <td colspan="2">&nbsp;</td>
                    <td class="text-center bold">12</td>
                    <td class="text-right bold">Total</td>
                    <td class="text-right bold">$600.00</td>
                    <td colspan="2">&nbsp;</td>
                </tr>
            </table>
        </div>
    </section>
    <div class="clearfix"></div>
</div>
<div id="reportDetail" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">123456</h4>
            </div>
            <div class="modal-body">
                <table class="report-tbl">
                    <tr>
                        <th>Status</th>
                        <td>Delivered</td>
                        <th>Ordered Date</th>
                        <td>07/12/2020</td>
                    </tr>
                    <tr>
                        <th>Ordered Time</th>
                        <td>09.30 am</td>
                        <th>Delivered Time</th>
                        <td>09.58 am</td>
                    </tr>
                    <tr>
                        <th>Ordered Taken By</th>
                        <td>Pramod Karkera</td>
                        <th>Order Prepared By</th>
                        <td>Sujeesh Soman</td>
                    </tr>
                    <tr>
                        <th>Ordered Packed By</th>
                        <td>Sony Reddy</td>
                        <th>Order Delivered By</th>
                        <td>Jayanth Joseph</td>
                    </tr>
                    <tr>
                        <th>Customer Name</th>
                        <td>Pxxxxd Kxxxxxa</td>
                        <th>Customer Phone No</th>
                        <td>9xxxxxxxx7</td>
                    </tr>
                </table>

                <h5 class="order-dtls">Order Details</h5>
                <table class="custom-tbl">
                    <tr>
                        <th class="text-center">Sl No</th>
                        <th class="text-center">Item Name</th>
                        <th class="text-center">Quantity</th>
                        <th class="text-center">Price</th>
                    </tr>
                    <tr>
                        <td class="text-center">01</td>
                        <td>Margherita</td>
                        <td class="text-center">01</td>
                        <td class="text-right">$150.00</td>
                    </tr>
                    <tr>
                        <td class="text-center">02</td>
                        <td>Peppy Paneer</td>
                        <td class="text-center">01</td>
                        <td class="text-right">$150.00</td>
                    </tr>
                    <tr>
                        <td class="text-center">03</td>
                        <td>Deluxe Veggie</td>
                        <td class="text-center">01</td>
                        <td class="text-right">$150.00</td>
                    </tr>
                    <tr>
                        <td class="bold text-center">03</td>
                        <td class="bold">&nbsp;</td>
                        <td class="bold text-center">03</td>
                        <td class="bold text-right">$600.00</td>
                    </tr>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

// KitchenKanban.WebUI/kitchenvue/src/views/Reports.vue
<template>
    <div>
        <div>
            <section>
                <div class="breadcrumb">
                    <div>Reports</div>
                    <div class="current-time">{{currentdate |formatTime}}</div>
                    <div class="clearfix"></div>
                </div>
                <div class="list-sec">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-xs-3">
                                &nbsp;
                            </div>
                            <div class="col-xs-6 text-center current-date">
                                {{currentdate |toDate}}
                            </div>
                            <div class="col-xs-3">
                                <input type="search" placeholder="Search Order" class="form-control" v-model.lazy="search" />
                            </div>
                        </div>
                    </div>
                    <table class="custom-tbl">
                        <tr>
                            <th class="text-center">Sl No</th>
                            <th class="text-center">Order No</th>
                            <th class="text-center">Order Time</th>
                            <th class="text-center">No of Dishes</th>
                            <th class="text-center">Order Taken By</th>
                            <th class="text-center">Order Value</th>
                            <th class="text-center">Order Status</th>
                            <th class="text-center">Detail</th>
                        </tr>
                        <tr class="custom-btl-row" v-for="(order,index) in filteredItems" :key="order.orderNumber">
                            <td class="text-center">{{index+1}}</td>
                            <td>{{order.orderNumber}}</td>
                            <td>{{order.orderDate |toTime }}</td>
                            <td class="text-center">{{order.noOfItemsInOrder}}</td>
                            <td>{{order.orderTakenByUserName}}</td>
                            <td class="text-right">{{order.orderAmount | toFixed | toUSD }}</td>
                            <td class="text-center">
                                <span v-if="order.orderStatus==1">NewOrder</span>
                                <span v-if="order.orderStatus==2">BeingPrepared</span>
                                <span v-if="order.orderStatus==3">Prepared</span>
                                <span v-if="order.orderStatus==4">Packing</span>
                                <span v-if="order.orderStatus==5">ReadyToBeDelivered</span>
                                <span v-if="order.orderStatus==6">Completed</span>
                                <span class="cancelled-order-status" v-if="order.orderStatus==7">Cancelled</span>
                            </td>
                            <td class="text-center">
                                <button class="trans-btn" data-toggle="modal" data-target="#reportDetail" @click="getOrderById(order.orderId)"><i class="glyphicon glyphicon-exclamation-sign"></i></button>
                            </td>
                        </tr>
                        <tr class="custom-btl-row">
                            <td colspan="3">&nbsp;</td>
                            <td class="text-center bold">{{totalqty}}</td>
                            <td class="text-right bold">Total</td>
                            <td class="text-right bold">{{totalamount |toFixed|toUSD}}</td>
                            <td colspan="2">&nbsp;</td>
                        </tr>

                    </table>
                </div>
            </section>
            <div class="clearfix"></div>
        </div>


        <div id="reportDetail" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">{{orderdetail.order.orderNumber}}</h4>
                    </div>
                    <div class="modal-body">
                        <table class="report-tbl">
                            <tr>
                                <th>Status</th>
                                <td>
                                    <span v-if="orderdetail.order.orderStatus==1">NewOrder</span>
                                    <span v-if="orderdetail.order.orderStatus==2">BeingPrepared</span>
                                    <span v-if="orderdetail.order.orderStatus==3">Prepared</span>
                                    <span v-if="orderdetail.order.orderStatus==4">Packing</span>
                                    <span v-if="orderdetail.order.orderStatus==5">ReadyToBeDelivered</span>
                                    <span v-if="orderdetail.order.orderStatus==6">Completed</span>
                                    <span class="cancelled-order-status" v-if="orderdetail.order.orderStatus==7">Cancelled</span>

                                </td>
                                <th>Ordered Date</th>
                                <td>{{orderdetail.order.orderDate |toDate}}</td>
                            </tr>
                            <tr>
                                <th>Ordered Time</th>
                                <td>{{orderdetail.order.orderDate|toTime}}</td>
                                <th>Delivered Time</th>
                                <td>
                                    <span v-if="orderdetail.order.orderDeliveryDate==null">  </span>
                                    <span v-else>{{orderdetail.order.orderDeliveryDate |toTime}}</span>
                                </td>
                            </tr>
                            <tr>
                                <th>Ordered Taken By</th>
                                <td>{{orderdetail.order.orderTakenByUserName}}</td>
                                <th>Customer Phone No</th>
                                <td>{{orderdetail.order.customerContactNumber?orderdetail.order.customerContactNumber.substring(0,4)+"*****":''}}</td>
                            </tr>
                            <tr>
                                <th>Customer Name</th>
                                <td>{{orderdetail.order.customerName?orderdetail.order.customerName.substring(0,3)+"*****":''}}</td>

                            </tr>
                        </table>

                        <h5 class="order-dtls">Order Details</h5>
                        <table class="custom-tbl">
                            <tr>
                                <th class="text-center"></th>
                                <th class="text-center">Item Name</th>
                                <th class="text-center">Quantity</th>
                                <th class="text-center">Price</th>
                            </tr>
                            <tr v-for="(data,index) in orderdetail.orderLines" :key="data.itemId">
                                <td class="text-center">{{index+1}}</td>
                                <td>{{data.itemName}}</td>
                                <td class="text-center">{{data.orderQuantity}}</td>
                                <td class="text-right">{{(data.orderQuantity)*(data.itemCharge)|toFixed|toUSD}}</td>
                            </tr>


                            <tr>
                                <td class="bold ">&nbsp;</td>
                                <td class="bold">&nbsp;</td>
                                <td class="bold text-center">{{totalitemcount}}</td>
                                <td class="bold text-right">{{totalitemamount|toFixed|toUSD}}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script src="../viewscripts/reportScript.js" type="text/javascript">

</script>
